[package]
name = "liars_poker_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
rand = "0.8"
log = "0.4"
stderrlog = "0.5"
clap = { version = "3.2", features = ["derive"] }
itertools = "0.10"
dyn-clone = "1.0"

