# File to define training profiles for cfr bot

[agents.baseline]
weight_file = "/var/lib/card_platypus/infostate.baseline"
training_iterations = 100000000
scoring_freq = 1000000
scoring_iterations = 1000
checkpoint_freq = 5000000
deal_type = "All"
no_normalize_suit = false
no_linear_cfr = false
single_thread = false
max_cards_played = 0

[agents.one_card_played]
weight_file = "/var/lib/card_platypus/infostate.one_card_played"
training_iterations = 100000000
scoring_freq = 1000000
scoring_iterations = 1000
checkpoint_freq = 5000000
deal_type = "All"
no_normalize_suit = false
no_linear_cfr = false
single_thread = false
max_cards_played = 1

[agents.two_card_played]
weight_file = "/var/lib/card_platypus/infostate.two_card_played"
training_iterations = 100000000
scoring_freq = 1000000
scoring_iterations = 1000
checkpoint_freq = 5000000
deal_type = "All"
no_normalize_suit = false
no_linear_cfr = false
single_thread = false
max_cards_played = 2