use running_emu::{World, find_path_bfs, print_map, print_path, print_world};

fn main() {
    let map = 
    "....S.....
    ..........
    ..........
    ..........
    ..........
    ....WWW...
    ....WGW...
    ....W.W...
    ..........";

    let world = World::from_map(map);

    print_world(&world);
    println!("");
    let path = find_path_bfs(&world);
    print_path(&path, &world);
    println!("");
    print_map(&world)

}