[package]
name = "euchre-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-router = "0.3.0"
dioxus-web = "0.3.2"
card_platypus =  { path = "../card_platypus" }
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"