[package]
name = "card_platypus"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
log = "0.4"
clap = { version = "4.3", features = ["derive"] }
itertools = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.1" # can be set to human readable for debugging
tempfile = "3.3"
serde-big-array = "0.5"
rustc-hash = "1.1.0"
approx = "0.5"
rayon = "1.7"
dashmap = {version = "5.4.0", features = ["serde"]}
indicatif = "0.17.5"
features = {version ="0.10", git = "https://github.com/swpecht/features-rs.git"}
bitflags = "2.4"
simplelog = "0.12"
num-traits = "0.2"
num-derive = "0.4"
anyhow = "1.0"
dyn-clone = "1.0"
toml = "0.7"
crossbeam-queue = "0.3"
thread_local = "1.1"
rusqlite = { version = "0.29.0", features = ["bundled"] }
heed = "0.11"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "game_benchmarks"
harness = false

[[bench]]
name = "agent_benchmarks"
harness = false

[[bench]]
name = "pimcts_optimizations"
harness = false

[[bench]]
name = "node_storage_benchmark"
harness = false
